"""add_saved_to_transactions_to_ocr_jobs

Revision ID: 0005
Revises: 0004
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_expense_jobs', sa.Column('saved_to_transactions', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocr_expense_jobs', 'saved_to_transactions')
    # ### end Alembic commands ###
